#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := display-socket

# Getting the components folder located in the parent directory of the current example
EXTRA_COMPONENT_DIRS = ../$(PARENT_DIR)/components

include $(IDF_PATH)/make/project.mk